def generate_arithmetic_exception():
    num1 = 10
    num2 = 0
    result = num1 / num2

generate_arithmetic_exception()