def throw_exception():
    num1 = 10
    num2 = 0
    result = num1 / num2

def main():
    throw_exception()

main()
